name: Build DCEVM version of OpenJDK JRE for OSX

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      outputname:
        description: 'Output filename'
        default: 'openjdk_jre_dcevm.tar.gz'
        required: false
        type: string
      jdk:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Temurin JDK'
        # Default value if no value is explicitly provided
        default: 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_mac_hotspot_11.0.20.1_1.tar.gz'

        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
        
      dcevm:
        description: 'DCEVM JDK'
        default: 'https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/download/dcevm-11.0.15%2B1/Openjdk11u-dcevm-mac-x64.tar.gz'
        required: true
        type: string
        
      jre:
        description: 'Temurin JRE'
        default: 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jre_x64_mac_hotspot_11.0.20.1_1.tar.gz'
        required: true
        type: string

jobs:
  confirm:
    runs-on: ubuntu-latest

    steps:
    - name: Confirm inputs
      run: |
        echo "Using ${{ inputs.jre }}"
        echo "Using ${{ inputs.jdk }}"
        echo "Using ${{ inputs.dcevm }}"
        echo "Using ${{ inputs.outputname }}"
      
  get-zipfiles:
    runs-on: ubuntu-latest
    steps:    
        # Checkout the branch first
      - name: checkout
        uses: actions/checkout@v2

      - name: wget dcevm
        uses: wei/wget@v1
        with:
          args: -O dcevm.tar.gz ${{ inputs.dcevm }}
          
      - name: wget openjdk
        uses: wei/wget@v1
        with:
          args: -O jdk.tar.gz ${{ inputs.jdk }}
          
      - name: wget openjre
        uses: wei/wget@v1
        with:
          args: -O jre.tar.gz ${{ inputs.jre }}          
  
      - name: ls
        run: |
          ls -asltr
          
      - name: extract from tar
        run: |
          mkdir dcevm && tar -C dcevm -xvf dcevm.tar.gz
          mkdir jdk && tar -C jdk -xvf jdk.tar.gz
          mkdir jre && tar -C jre -xvf jre.tar.gz
          
      - name: list contents
        run: |
          ls -asltr
          echo "dcevm" && ls -asl dcevm/
          echo "jdk" && ls -asl jdk/
          echo "jre" && ls -asl jre/
          
      - name: Copy files
        run: |
          # Copy {TravaJDK Directory}/Contents/Home/lib/server/libjvm.dylib to {JRE Directory}/Contents/Home/lib/server/libjvm.dylib
          cp dcevm/*/Contents/Home/lib/server/libjvm.dylib jre/*/Contents/Home/lib/server/libjvm.dylib
          # Copy {AdoptOpenJDK Directory}/Contents/Home/lib/modules to {JRE Directory}/Contents/Home/lib/modules
          cp jdk/*/Contents/Home/lib/modules  jre/*/Contents/Home/lib/modules
          echo "ls -asl " && ls -asl
          mkdir -p osx
          cd jre && tar -zcvf ../osx/${{ inputs.outputname }} *
          
      - name: Commit message
        run: |
          pwd
          echo "New DCEVM tar.gz for OSX built from:" > info.txt
          echo "JRE ${{ inputs.jre }}" >> info.txt
          echo "JDK  ${{ inputs.jdk }}" >> info.txt
          echo "DCEVM ${{ inputs.dcevm }}" >> info.txt
          echo "Output ${{ inputs.outputname }}" >> info.txt
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:    # Artifact name
          name: ${{ inputs.outputname }} 
          path: osx/${{ inputs.outputname }}
        
      - name: Upload Build info
        uses: actions/upload-artifact@v3.1.3
        with:
          name: info.txt
          path: info.txt
    
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          rm -fr dcevm jdk jre
          rm -fr dcevm.tar.gz jdk.tar.gz jre.tar.gz
          # Stage the file, commit and push
          git add osx/${{ inputs.outputname }} 
          git commit -m "New DCEVM build for OSX"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5          
        with:
          add-paths: | # specifically add this zip file
            osx/${{ inputs.outputname }}
          body-path: info.txt
          title: New DCEVM build for OSX
          
