# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      jre:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'OpenJDK'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      jdk:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Trava'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  confirm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ inputs.jre }}"
        echo "Hello ${{ inputs.jdk }}"
        env
      
  get-zipfiles:
    runs-on: ubuntu-latest
    steps:
      - name: wget dcevm
        uses: wei/wget@v1
        with:
          args: https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/download/dcevm-11.0.15+1/Openjdk11u-dcevm-windows-x64.zip
      - name: wget openjdk
        uses: wei/wget@v1
        with:
          args: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1+1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.zip
      - name: wget openjre
        uses: wei/wget@v1
        with:
          args: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1+1/OpenJDK11U-jre_x64_windows_hotspot_11.0.20.1_1.zip          
      - name: ls
        run: |
          ls -asltr
          
      - name: unzip all
        run: |
          unzip Openjdk11u-dcevm-windows-x64.zip
          unzip OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.zip
          unzip OpenJDK11U-jre_x64_windows_hotspot_11.0.20.1_1.zip
          
      - name: list contents
        run: |
          ls -asltr
          echo "dcevm-11.0.15+1" && ls -asl dcevm-11.0.15+1
          echo "jdk-11.0.20.1+1/" && ls -asl jdk-11.0.20.1+1/
          echo "jdk-11.0.20.1+1-jre" && ls -asl jdk-11.0.20.1+1-jre/
          
      - name: Copy files
        run: |
          # Copy {TravaJDK Directory}/bin/server/jvm.dll to {JRE Directory}/bin/server/jvm.dll
          cp dcevm-11.0.15+1/bin/server/jvm.dll jdk-11.0.20.1+1-jre/bin/server/jvm.dll
          # Copy {AdoptOpenJDK Directory}/lib/modules to {JRE Directory}/lib/modules
          cp jdk-11.0.20.1+1/lib/modules  jdk-11.0.20.1+1-jre/lib/modules
          mkdir windows-x64
          zip -r windows-x64/jdk-11.0.20.1+1-jre-dcevm.zip jdk-11.0.20.1+1-jre

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:    # Artifact name
          name: jdk-11.0.20.1+1-jre-dcevm.zip
          path: windows-x64/jdk-11.0.20.1+1-jre-dcevm.zip
          retention-days: 90

        # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add windows-x64
          git commit -m "New DCEVM build"
          git push origin master
      
          
